#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="C:\\INETPUB\\ARQSI\\MUSICPREFERENCES\\APP_DATA\\DATABASE.MDF")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertPreference(Preference instance);
  partial void UpdatePreference(Preference instance);
  partial void DeletePreference(Preference instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["C__INETPUB_ARQSI_MUSICPREFERENCES_APP_DATA_DATABASE_MDFConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Preference> Preferences
	{
		get
		{
			return this.GetTable<Preference>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Preferences")]
public partial class Preference : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _PlaylistId;
	
	private string _MusicName;
	
	private string _GenreName;
	
	private string _AlbumName;
	
	private string _ArtistName;
	
	private string _UserAge;
	
	private string _UserAddress;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPlaylistIdChanging(string value);
    partial void OnPlaylistIdChanged();
    partial void OnMusicNameChanging(string value);
    partial void OnMusicNameChanged();
    partial void OnGenreNameChanging(string value);
    partial void OnGenreNameChanged();
    partial void OnAlbumNameChanging(string value);
    partial void OnAlbumNameChanged();
    partial void OnArtistNameChanging(string value);
    partial void OnArtistNameChanged();
    partial void OnUserAgeChanging(string value);
    partial void OnUserAgeChanged();
    partial void OnUserAddressChanging(string value);
    partial void OnUserAddressChanged();
    #endregion
	
	public Preference()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaylistId", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string PlaylistId
	{
		get
		{
			return this._PlaylistId;
		}
		set
		{
			if ((this._PlaylistId != value))
			{
				this.OnPlaylistIdChanging(value);
				this.SendPropertyChanging();
				this._PlaylistId = value;
				this.SendPropertyChanged("PlaylistId");
				this.OnPlaylistIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusicName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string MusicName
	{
		get
		{
			return this._MusicName;
		}
		set
		{
			if ((this._MusicName != value))
			{
				this.OnMusicNameChanging(value);
				this.SendPropertyChanging();
				this._MusicName = value;
				this.SendPropertyChanged("MusicName");
				this.OnMusicNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenreName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string GenreName
	{
		get
		{
			return this._GenreName;
		}
		set
		{
			if ((this._GenreName != value))
			{
				this.OnGenreNameChanging(value);
				this.SendPropertyChanging();
				this._GenreName = value;
				this.SendPropertyChanged("GenreName");
				this.OnGenreNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string AlbumName
	{
		get
		{
			return this._AlbumName;
		}
		set
		{
			if ((this._AlbumName != value))
			{
				this.OnAlbumNameChanging(value);
				this.SendPropertyChanging();
				this._AlbumName = value;
				this.SendPropertyChanged("AlbumName");
				this.OnAlbumNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArtistName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string ArtistName
	{
		get
		{
			return this._ArtistName;
		}
		set
		{
			if ((this._ArtistName != value))
			{
				this.OnArtistNameChanging(value);
				this.SendPropertyChanging();
				this._ArtistName = value;
				this.SendPropertyChanged("ArtistName");
				this.OnArtistNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAge", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string UserAge
	{
		get
		{
			return this._UserAge;
		}
		set
		{
			if ((this._UserAge != value))
			{
				this.OnUserAgeChanging(value);
				this.SendPropertyChanging();
				this._UserAge = value;
				this.SendPropertyChanged("UserAge");
				this.OnUserAgeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string UserAddress
	{
		get
		{
			return this._UserAddress;
		}
		set
		{
			if ((this._UserAddress != value))
			{
				this.OnUserAddressChanging(value);
				this.SendPropertyChanging();
				this._UserAddress = value;
				this.SendPropertyChanged("UserAddress");
				this.OnUserAddressChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
